version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: curricura
      POSTGRES_USER: curricura
      POSTGRES_PASSWORD: curricura
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8020:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://curricura:curricura@db:5432/curricura

  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  pgdata:
