# Generated by Django 5.2.4 on 2025-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptupload',
            name='cleaned_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptupload',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
