# Generated by Django 5.2.4 on 2025-07-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_transcriptchunk_videotranscript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranscript',
            name='course_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='course_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
