# Generated by Django 5.2.4 on 2025-07-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_videotranscript_transcriptchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptchunk',
            name='transcript_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
