# Generated by Django 5.2.4 on 2025-07-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_videotranscript_course_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.BigIntegerField()),
                ('course_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('html_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('points_possible', models.FloatField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_canvas', models.DateTimeField(blank=True, null=True)),
                ('updated_at_canvas', models.DateTimeField(blank=True, null=True)),
                ('submission_types', models.JSONField()),
                ('external_tool_url', models.URLField(blank=True, null=True)),
                ('full_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('canvas_file_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.SlugField()),
                ('canvas_course_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
