# Generated by Django 5.2.4 on 2025-07-16 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvasassignment',
            old_name='course_id',
            new_name='canvas_course_id',
        ),
        migrations.AddField(
            model_name='canvasassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_assignments', to='ingest.course'),
        ),
        migrations.AddField(
            model_name='canvasfile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_files', to='ingest.course'),
        ),
        migrations.AddField(
            model_name='canvaspage',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_pages', to='ingest.course'),
        ),
    ]
