# Generated by Django 5.2.4 on 2025-07-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_rename_course_id_canvasassignment_canvas_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvaspage',
            name='url',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='canvasassignment',
            unique_together={('assignment_id', 'canvas_course_id')},
        ),
        migrations.AlterUniqueTogether(
            name='canvasfile',
            unique_together={('canvas_file_id', 'course')},
        ),
    ]
