# Generated by Django 5.2.4 on 2025-07-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_alter_canvaspage_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasassignment',
            name='cleaned_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvasfile',
            name='cleaned_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvaspage',
            name='cleaned_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
