# Generated by Django 5.2.4 on 2025-07-18 07:28

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0008_canvasassignment_cleaned_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(choices=[('file', 'File'), ('page', 'Page'), ('assignment', 'Assignment')], max_length=20)),
                ('parent_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['parent_type', 'parent_id'], name='ingest_canv_parent__f8902f_idx')],
            },
        ),
    ]
