# Generated by Django 5.2.4 on 2025-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_canvaschunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasfile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
