# Generated by Django 5.2.4 on 2025-07-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_canvasfile_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvasfile',
            old_name='url',
            new_name='file_url',
        ),
    ]
