# Generated by Django 5.2.4 on 2025-07-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0011_rename_url_canvasfile_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranscript',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_transcripts', to='ingest.course'),
        ),
    ]
