# Generated by Django 5.2.4 on 2025-07-21 09:22

from django.db import migrations

def forwards_func(apps, schema_editor):
    Course = apps.get_model('ingest', 'Course')
    VideoTranscript = apps.get_model('ingest', 'VideoTranscript')

    for vt in VideoTranscript.objects.all():
        if vt.course_code and vt.course_title:
            course, _ = Course.objects.get_or_create(
                code=vt.course_code,
                defaults={"title": vt.course_title, "year": vt.year}
            )
            vt.course = course
            vt.save()

def reverse_func(apps, schema_editor):
    # No reverse migration needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0012_videotranscript_course'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
