# Generated by Django 5.2.4 on 2025-07-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0013_populate_video_transcript_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotranscript',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='videotranscript',
            name='course_title',
        ),
    ]
