# Generated by Django 5.2.4 on 2025-07-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ingest', '0014_remove_videotranscript_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='courses', to='core.school'),
        ),
    ]
